### ISSUE TITLE
calibration 

### ISSUE THREAD

**Issue by wangxdflight** [OpenFTC/EOCV-AprilTag-Plugin#3]
Any details on how to do the calibration for code below? We want to use apriltag on the signal sleeve for this season, but it is curved surface. Wondering if the calibration can address this specifics.

Thanks in advance!

https://github.com/OpenFTC/EOCV-AprilTag-Plugin/blob/master/examples/src/main/java/org/firstinspires/ftc/teamcode/AprilTagAutonomousInitDetectionExample.java#L47

    // NOTE: this calibration is for the C920 webcam at 800x448.
    // You will need to do your own calibration for other configurations!
    double fx = 578.272;
    double fy = 578.272;
    double cx = 402.145;
    double cy = 221.506;

**Comment by Windwoes** [comment]
Calibration won't help with a curved tag. The calibration is to correct for lens distortion. 
Additionally, the calibration is only used for postion computation, not for detection. Making the tag smaller may help you avoid issues caused by the distortion of wrapping it around a cone.
