### ISSUE TITLE
Can you publish an aar file?

### ISSUE THREAD

**Issue by egarland** [OpenFTC/EOCV-AprilTag-Plugin#4]
I was able to create an .aar file from the project but it took me a while to figure out how to do it.  It would be good if there was one available to download so that people could easily add this to their robot in a way that they can use it with the OnBot Java build system.  We develop in Android Studio but push the code to the robot and build using OnBot.

**Comment by Windwoes** [comment]
The AAR is available from maven :) 
https://repo1.maven.org/maven2/org/openftc/apriltag/1.1.0/apriltag-1.1.0.aar

**Comment by egarland** [comment]
Ooh.  Thanks!

**Comment by ItsHarper** [comment]
This information should probably be in the README, like it is for EOCV.

**Comment by Windwoes** [comment]
Readme updated in https://github.com/OpenFTC/EOCV-AprilTag-Plugin/commit/10f3e42e14575b353ad60e86cb3ef7a68ca46ab5
